---
- hosts: all
  become: true  # Optional: needed if creating file in a privileged path
  tasks:
    - name: Creating an empty file
      ansible.builtin.file:
        path: /tmp/myfile.txt  # Replace with your desired path
        state: touch
        mode: '0644'  # Optional: file permission
